// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vsxyzaifvemjcnmllzhw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZzeHl6YWlmdmVtamNubWxsemh3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwNzMwNzEsImV4cCI6MjA2ODY0OTA3MX0.BPUq57BDYNq5ocJJc8xfZR_TQmr79u1r3zrqL7PVQfA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});